### ISSUE TITLE
Add option to exclude packages supplied by modules on which we have a runtime dep

### ISSUE THREAD

**Issue by mbooth101** [fedora-java/modularity-utils#10]
My tycho module has a runtime dependency on javapackages-tools, so there's no point in rebuilding anything for my module that is already supplied by javapackages-tools.

Right now, I generate an excludes list that contains all the packages from my runtime deps and add that manually to my koschie.cfg, for example:

```
#!/bin/bash

function gen_pkg_excludes() {
        echo "        # Packages from $1 module"
        for pkg in $(koji list-pkgs --quiet --tag=$2 | cut -d' ' -f1 | sort) ; do
                echo "        \"$pkg\","
        done
}

gen_pkg_excludes javapackages-tools module-javapackages-tools-201801-2820190413130040-819b5873
```

But maybe the script should automatically exclude these from the dep-solving process

**Comment by mizdebsk** [comment]
@mbooth101 You should be able to exclude contests of javapackages-tools module now. Explicit includes have precedence over excludes. Example usage in `koschei.cfg`:

```
    "module_excludes": {
        ("javapackages-tools", "201801"),
    },
```
